eclipseplugin:
  dupe:
    itemlimit: 50
    active: true
    timeout: 15000
  roof:
    speed: 15
    lowtps: 16
    lowspeed: 10
    offtps: 10
    killifabove: false
  culling:
    time: -1
  dura:
    active: true
  shield:
    active: true
  home:
    maxhomes: 5
    tptime: 3000
  tpa:
    active: false
    timeout: 10000
  stats:
    starttime: 0
    worldfolders:
      - "world"
      - "world_nether"
      - "world_the_end"
    command:
      - "&6--------------------------------------------"
      - "&7World was created on &6[STARTDATE]&7. That was &6[DURATION]&7 ago."
      - "&7The world is &6[SIZE]&7."
      - "&7A total of &6[PLAYERS]&7 players have joined."
      - "&7World seed: [[SEED]]"
      - "&6--------------------------------------------"