name: EclipsePlugin
version: 0.2
authors: [opfromthestart]
main: com.gmail.opfromthestart.Main
api-version: 1.18
commands:
  dupe:
    description: Dupe settings
    usage: /dupe [active | itemlimit | timeout] [number | bool]
    permission: eclipseplugin.dupe.command
permissions:
  eclipseplugin:
    dupe:
      command:
        default: op
      use:
        default: true