name: EclipsePlugin
version: 0.3
authors: [opfromthestart]
main: com.gmail.opfromthestart.Main
api-version: 1.18
depend: ["ProtocolLib"]
commands:
  dupe:
    description: Dupe settings
    usage: /dupe [active | itemlimit | timeout] [number | bool]
    permission: eclipseplugin.dupe.command
  roof:
    description: Nether roof settings
    usage: /roof [offtps | lowtps | slowspeed | maxspeed | killifabove] [speed]
    permission: eclipseplugin.roof.command
  culltime:
    description: Chunk culling time
    usage: /culltime or /culltime [ticks]
    permission: eclipseplugin.cull.command
  shield:
    description: Shield meta toggle
    usage: /shield or /shield [true | false]
    permission: eclipseplugin.shield.command
  dura:
    description: Dura tools toggle
    usage: /dura or /dura [true | false]
    permission: eclipseplugin.dura.command
  home:
    description: Home command
    usage: /home [tp | add | remove | list]
    permission: eclipseplugin.home.command
  homelimit:
    description: Home settings command
    usage: /homelimit [maxhomes | tptime] [limit]
    permission: eclipseplugin.homelimit.command
  tpa:
    description: Sends a teleport request
    usage: /tpa [player]
    permission: eclipseplugin.tpa.command
  tpy:
    description: Accepts a teleport request
    usage: /tpy [none|player]
    permission: eclipseplugin.tpa.command
  tpn:
    description: Denies a teleport request
    usage: /tpn [none|player]
    permission: eclipseplugin.tpa.command
  tpsett:
    description: Modify tpa
    usage: /tpsett [active|timeout] [value | none]
    permission: eclipseplugin.tpsett.command
permissions:
  eclipseplugin:
    dupe:
      command:
        default: op
      use:
        default: true
    roof:
      command:
        default: op
    cull:
      command:
        default: op
    shield:
      command:
        default: op
    dura:
      command:
        default: op
    home:
      command:
        default: op
    homelimit:
      command:
        default: true
    tpa:
      command:
        default: true
    tpsett:
      command:
        default: op